auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  receivers:                          
    jaeger:                           
      protocols:                      
        thrift_http:                  
        grpc:                         
        thrift_binary:
        thrift_compact:
    zipkin:
    otlp:
      protocols:
        http:
        grpc:
    opencensus:

ingester:
  trace_idle_period: 10s              
  traces_per_block: 100               
  max_block_duration: 5m              

compactor:
  compaction:
    compaction_window: 1h             
    max_compaction_objects: 1000000   
    block_retention: 1h
    compacted_block_retention: 10m

storage:
  trace:
    backend: local                    
    wal:
      path: /tmp/tempo/wal            
      bloom_filter_false_positive: .05
      index_downsample: 10            
    local:
      path: /tmp/tempo
    pool:
      max_workers: 100                
      queue_depth: 10000